# Generated by Django 5.2 on 2026-01-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_is_paid_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
